# Generated by Erlang.mk. Edit at your own risk!

src/currentProcesses.erl:: src/physics.erl; @touch $@
src/szybcy_i_autonomiczni_sup.erl:: src/currentProcesses.erl src/fifoQueue.erl src/resultsBase.erl; @touch $@

COMPILE_FIRST += physics currentProcesses resultsBase fifoQueue
